package main

import (
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// updateGolden regenerates want.txt when -update is passed.
//
//	go test -run TestGolden -update
var updateGolden = flag.Bool("update", false, "regenerate golden want.txt files")

// TestGolden runs every subdirectory of testdata/ as an independent test case.
// Each directory must contain:
//
//	source_NN.diff  - one or more source-PR diffs (NN = 00, 01, ...)
//	backport.diff   - the backport-PR diff
//	want.txt        - expected buildReport output (generated by -update)
func TestGolden(t *testing.T) {
	entries, err := os.ReadDir("testdata")
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		entry := entry
		t.Run(entry.Name(), func(t *testing.T) {
			t.Parallel()
			dir := filepath.Join("testdata", entry.Name())
			got := runGoldenCase(t, dir)

			wantPath := filepath.Join(dir, "want.txt")
			if *updateGolden {
				if err := os.WriteFile(wantPath, []byte(got), 0644); err != nil {
					t.Fatalf("write %s: %v", wantPath, err)
				}
				t.Logf("updated %s", wantPath)
				return
			}

			wantBytes, err := os.ReadFile(wantPath)
			if err != nil {
				t.Fatalf("read %s: %v (run with -update to create it)", wantPath, err)
			}
			want := string(wantBytes)
			if got == want {
				return
			}

			// Line-level diff for readable failure messages.
			gotLines := strings.Split(got, "\n")
			wantLines := strings.Split(want, "\n")
			maxLen := len(gotLines)
			if len(wantLines) > maxLen {
				maxLen = len(wantLines)
			}
			t.Errorf("output mismatch for %s", entry.Name())
			for i := 0; i < maxLen; i++ {
				var g, w string
				if i < len(gotLines) {
					g = gotLines[i]
				}
				if i < len(wantLines) {
					w = wantLines[i]
				}
				if g != w {
					t.Logf("line %d:\n  got:  %q\n  want: %q", i+1, g, w)
				}
			}
		})
	}
}

// runGoldenCase loads the diff fixtures from dir and returns the buildReport output.
func runGoldenCase(t *testing.T, dir string) string {
	t.Helper()

	// Accumulate source PRs in sorted filename order.
	sources, _ := filepath.Glob(filepath.Join(dir, "source_*.diff"))
	sort.Strings(sources)

	masterFiles := make(map[string][]string)
	masterIgnored := make(map[string]struct{})
	sourcePRNums := make([]int, len(sources))

	for i, srcPath := range sources {
		sourcePRNums[i] = 100 + i
		diffText, err := os.ReadFile(srcPath)
		if err != nil {
			t.Fatalf("read %s: %v", srcPath, err)
		}
		normalized, err := normalizeDiff(string(diffText))
		if err != nil {
			t.Fatalf("normalizeDiff %s: %v", srcPath, err)
		}
		mergeFileMaps(masterFiles, normalized.Files)
		addIgnored(masterIgnored, normalized.Ignored)
	}
	// Fall back to a single stub source PR when no source files exist.
	if len(sourcePRNums) == 0 {
		sourcePRNums = []int{100}
	}

	backportBytes, err := os.ReadFile(filepath.Join(dir, "backport.diff"))
	if err != nil {
		t.Fatalf("read backport.diff: %v", err)
	}
	backportNormalized, err := normalizeDiff(string(backportBytes))
	if err != nil {
		t.Fatalf("normalizeDiff backport.diff: %v", err)
	}

	return buildReport(
		"acme/myrepo",
		pullRequest{Number: 200, Title: "Test backport"},
		sourceResolution{Numbers: sourcePRNums, Method: "body markers"},
		masterFiles,
		backportNormalized,
		masterIgnored,
	)
}
